branches:
  only:
  - source
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
- pip install https://github.com/davisp/ghp-import/archive/master.zip
script:
- make travis
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: SJJyfFj/YzcAiZce/7rcl8dpqfVwNGk7g6u+N+uVH/KvVPVdh6H7c3Pp/TvVvHoFaTQKyj2rMxon+X1cjHzF1/d7oJuwwXgrh9hFIcssx2m3TRCi1Z7Cv/czptIM7zxoPvRJb83f4wdyxOJW5AQ6HrI0vfkhc12gmgP6JKGGbvU=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
